//! Material Symbols Rounded, the icon set the design draws with.
//!
//! It is a ligature font: the glyph is selected by writing its *name* as text —
//! `check`, `play_arrow` — and the font substitutes the symbol. So an icon here
//! is a text run in a particular family, not an SVG or a codepoint, which is
//! also why the family name has to match exactly or you get the literal word.

use gpui::*;

/// The family as the bundled file registers itself.
pub const FAMILY: &str = "Material Symbols Rounded";

/// Names used by the design, as the codepoints the subset font maps.
///
/// Material Symbols is normally driven as a ligature font — write `play_arrow`
/// and the font substitutes the symbol. That is why the whole 6,597-glyph file
/// used to ship: the forty names between them use most of the alphabet, so
/// subsetting by text kept every icon spellable from those letters. Addressing
/// each glyph by its own codepoint drops the ligature table and the letters
/// with it, and takes the bundled font from 15 MB to 80 KB.
///
// Generated by scripts/make-icon-font.py — regenerate rather than edit.
pub mod name {
    pub const CHECK: &str = "\u{e668}"; // check
    pub const PLAY_ARROW: &str = "\u{e037}"; // play_arrow
    pub const PLAY_CIRCLE: &str = "\u{e1c4}"; // play_circle
    pub const PAUSE: &str = "\u{e034}"; // pause
    pub const PAUSE_CIRCLE: &str = "\u{e1a2}"; // pause_circle
    pub const MIC: &str = "\u{e31d}"; // mic
    pub const ADD: &str = "\u{e145}"; // add
    pub const SETTINGS: &str = "\u{e8b8}"; // settings
    pub const EXPAND_MORE: &str = "\u{e5cf}"; // expand_more
    pub const EXPAND_LESS: &str = "\u{e5ce}"; // expand_less
    pub const CHECK_CIRCLE: &str = "\u{f0be}"; // check_circle
    pub const HARD_DRIVE: &str = "\u{f80e}"; // hard_drive
    pub const TUNE: &str = "\u{e429}"; // tune
    pub const WIFI_OFF: &str = "\u{e648}"; // wifi_off
    pub const DOWNLOAD: &str = "\u{f090}"; // download
    pub const DOWNLOADING: &str = "\u{f001}"; // downloading
    pub const UPLOAD_FILE: &str = "\u{e9fc}"; // upload_file
    pub const WARNING: &str = "\u{f083}"; // warning
    pub const INFO: &str = "\u{e88e}"; // info
    pub const GRAPHIC_EQ: &str = "\u{e1b8}"; // graphic_eq
    pub const LOCK: &str = "\u{e899}"; // lock
    pub const CLOSE: &str = "\u{e5cd}"; // close
    pub const STOP_CIRCLE: &str = "\u{ef71}"; // stop_circle
    pub const FOLDER_OPEN: &str = "\u{e2c8}"; // folder_open
    pub const BLOCK: &str = "\u{f08c}"; // block
    pub const DELETE: &str = "\u{e92e}"; // delete
    pub const OPEN_IN_NEW: &str = "\u{e89e}"; // open_in_new
    pub const HEADPHONES: &str = "\u{f01f}"; // headphones
    pub const REFRESH: &str = "\u{e5d5}"; // refresh
    pub const CONTENT_COPY: &str = "\u{e14d}"; // content_copy
    pub const RADIO_UNCHECKED: &str = "\u{e836}"; // radio_button_unchecked
    pub const MEMORY: &str = "\u{e322}"; // memory
    pub const EDIT_NOTE: &str = "\u{e745}"; // edit_note
    pub const MORE_HORIZ: &str = "\u{e5d3}"; // more_horiz
    pub const EDIT: &str = "\u{f097}"; // edit
    pub const PROGRESS: &str = "\u{e9d0}"; // progress_activity
    pub const RECORD_VOICE: &str = "\u{e91f}"; // record_voice_over
    pub const PANEL_OPEN: &str = "\u{f704}"; // right_panel_open
    pub const PANEL_CLOSE: &str = "\u{f705}"; // right_panel_close
    pub const CASINO: &str = "\u{eb40}"; // casino
    pub const DESCRIPTION: &str = "\u{e873}"; // description
}
/// One icon at a given size and colour.
pub fn icon(glyph: &'static str, size: f32, colour: Hsla) -> impl IntoElement {
    face(FAMILY, glyph.to_string(), size, colour)
}

/// The solid version, for the glyphs the design draws filled: the chosen voice,
/// the clip that is playing, the transport itself.
///
/// Material Symbols keeps its filled variants both on a `FILL` variable-font
/// axis and as explicit `<name>.fill` glyphs. gpui puts OpenType features on a
/// font but not variable-font axes, so the axis cannot be reached from here —
/// and a separate filled family does not resolve under gpui's font loading at
/// all. `scripts/make-filled-icon-font.py` therefore points a private-use
/// codepoint at each `.fill` glyph inside the one bundled file, and this
/// addresses them by that codepoint. A name with no filled cut falls back to
/// the outline.
pub fn filled(glyph: &'static str, size: f32, colour: Hsla) -> impl IntoElement {
    face(FAMILY, filled_char(glyph).unwrap_or_else(|| glyph.to_string()), size, colour)
}

/// Printed by `scripts/make-filled-icon-font.py` when it writes the font, so
/// the two can be checked against each other rather than trusted.
fn filled_char(glyph: &str) -> Option<String> {
    let c = match glyph {
        name::CHECK_CIRCLE => '\u{f0000}',
        name::PLAY_CIRCLE => '\u{f0001}',
        name::PAUSE_CIRCLE => '\u{f0002}',
        name::PLAY_ARROW => '\u{f0003}',
        name::PAUSE => '\u{f0004}',
        name::STOP_CIRCLE => '\u{f0005}',
        _ => return None,
    };
    Some(c.to_string())
}

fn face(family: &'static str, glyph: String, size: f32, colour: Hsla) -> impl IntoElement {
    div()
        .font_family(family)
        .text_size(px(size))
        .text_color(colour)
        .line_height(px(size))
        .child(glyph)
}
