[package]
name = "yarngo-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
yarngo-core = { path = "../core" }
rusqlite = { version = "0.32", features = ["bundled"] }
thiserror = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = "3"
yarngo-testing = { path = "../testing" }
serde_json = { workspace = true }
